insert into songs (Title, Artist, Genre) values ('Midnight Serenade', 'David Wilson', 'Metal');
insert into songs (Title, Artist, Genre) values ('Echoes of Eden', 'John Johnson', 'Indie');
insert into songs (Title, Artist, Genre) values ('Starlight Symphony', 'Amelia Adams', 'Country');
insert into songs (Title, Artist, Genre) values ('Melancholy Melody', 'Charlotte Flores', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Amber Aura', 'Sophia Garcia', 'Country');
insert into songs (Title, Artist, Genre) values ('Whispers in the Wind', 'Samantha Lee', 'Classical');
insert into songs (Title, Artist, Genre) values ('Sunset Dreams', 'John Johnson', 'Folk');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Matthew Lopez', 'Soul');
insert into songs (Title, Artist, Genre) values ('Starlight Symphony', 'Ella Murphy', 'Folk');
insert into songs (Title, Artist, Genre) values ('Mystic Melody', 'Ella Murphy', 'Soul');
insert into songs (Title, Artist, Genre) values ('Siren''s Song', 'Amelia Adams', 'Folk');
insert into songs (Title, Artist, Genre) values ('Sunset Dreams', 'Luna Cooper', 'EDM');
insert into songs (Title, Artist, Genre) values ('Sunset Dreams', 'James Perez', 'Punk');
insert into songs (Title, Artist, Genre) values ('Radiant Reverie', 'James Perez', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Echoes of Eden', 'Alice Smith', 'Metal');
insert into songs (Title, Artist, Genre) values ('Amber Aura', 'Matthew Lopez', 'Indie');
insert into songs (Title, Artist, Genre) values ('Lavender Lullaby', 'Isabella Gonzalez', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Cascade of Dreams', 'Michael Brown', 'Soul');
insert into songs (Title, Artist, Genre) values ('Velvet Visions', 'Ethan Ramirez', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Sunset Dreams', 'Daniel Thompson', 'Folk');
insert into songs (Title, Artist, Genre) values ('Lavender Lullaby', 'Olivia Martinez', 'Blues');
insert into songs (Title, Artist, Genre) values ('Melancholy Melody', 'Owen Stewart', 'Indie');
insert into songs (Title, Artist, Genre) values ('Luminous Lullaby', 'Ella Murphy', 'Pop');
insert into songs (Title, Artist, Genre) values ('Sapphire Skies', 'Daniel Thompson', 'Blues');
insert into songs (Title, Artist, Genre) values ('Ethereal Echo', 'Harper Coleman', 'Country');
insert into songs (Title, Artist, Genre) values ('Celestial Symphony', 'Ethan Ramirez', 'Pop');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'David Wilson', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Celestial Symphony', 'Emily Davis', 'Folk');
insert into songs (Title, Artist, Genre) values ('Lavender Lullaby', 'Henry Reed', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Silver Lining', 'Owen Stewart', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Amber Aura', 'Luna Cooper', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Sunset Dreams', 'Ava Hernandez', 'Classical');
insert into songs (Title, Artist, Genre) values ('Rainbow Rhapsody', 'Alice Smith', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Whimsical Waltz', 'Charlotte Flores', 'Pop');
insert into songs (Title, Artist, Genre) values ('Majestic Melody', 'Amelia Adams', 'Soul');
insert into songs (Title, Artist, Genre) values ('Moonlit Mirage', 'Ethan Ramirez', 'EDM');
insert into songs (Title, Artist, Genre) values ('Mystic Melody', 'Henry Reed', 'Soul');
insert into songs (Title, Artist, Genre) values ('Summer Breeze', 'David Wilson', 'Rock');
insert into songs (Title, Artist, Genre) values ('Moonlit Mirage', 'Alice Smith', 'R&B');
insert into songs (Title, Artist, Genre) values ('Velvet Visions', 'Henry Reed', 'Rock');
insert into songs (Title, Artist, Genre) values ('Velvet Visions', 'James Perez', 'Indie');
insert into songs (Title, Artist, Genre) values ('Whispering Willow', 'Ethan Ramirez', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Sunset Dreams', 'Ella Murphy', 'Indie');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Alexander Cruz', 'EDM');
insert into songs (Title, Artist, Genre) values ('Siren''s Song', 'John Johnson', 'Soul');
insert into songs (Title, Artist, Genre) values ('Echoes of Eternity', 'Samantha Lee', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Whirlwind Waltz', 'Luna Cooper', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Echoes of Eternity', 'Amelia Adams', 'EDM');
insert into songs (Title, Artist, Genre) values ('Starry Night', 'Luna Cooper', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Eternal Embrace', 'Daniel Thompson', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Silver Lining', 'Ella Murphy', 'Metal');
insert into songs (Title, Artist, Genre) values ('Emerald Echoes', 'Ethan Ramirez', 'Folk');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Isabella Gonzalez', 'Soul');
insert into songs (Title, Artist, Genre) values ('Lavender Lullaby', 'Luna Cooper', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Serenity Song', 'Emily Davis', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Rainbow Rhapsody', 'Mia Torres', 'Blues');
insert into songs (Title, Artist, Genre) values ('Tranquil Twilight', 'Isabella Gonzalez', 'R&B');
insert into songs (Title, Artist, Genre) values ('Melancholy Melody', 'Ella Murphy', 'EDM');
insert into songs (Title, Artist, Genre) values ('Whirlwind Waltz', 'David Wilson', 'Metal');
insert into songs (Title, Artist, Genre) values ('Silent Serenade', 'Daniel Thompson', 'R&B');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Owen Stewart', 'Indie');
insert into songs (Title, Artist, Genre) values ('Silent Serenade', 'Charlotte Flores', 'Blues');
insert into songs (Title, Artist, Genre) values ('Velvet Visions', 'Sophia Garcia', 'Soul');
insert into songs (Title, Artist, Genre) values ('Summer Breeze', 'Samantha Lee', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Golden Horizon', 'Isabella Gonzalez', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Harper Coleman', 'Rock');
insert into songs (Title, Artist, Genre) values ('Starlight Symphony', 'John Johnson', 'Soul');
insert into songs (Title, Artist, Genre) values ('Whirlwind Waltz', 'Daniel Thompson', 'Folk');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'James Perez', 'Classical');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'David Wilson', 'Blues');
insert into songs (Title, Artist, Genre) values ('Golden Horizon', 'Ava Hernandez', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Silver Lining', 'Ethan Ramirez', 'Punk');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Sophia Garcia', 'Blues');
insert into songs (Title, Artist, Genre) values ('Tranquil Twilight', 'Samantha Lee', 'Indie');
insert into songs (Title, Artist, Genre) values ('Silent Serenade', 'Henry Reed', 'R&B');
insert into songs (Title, Artist, Genre) values ('Ethereal Echo', 'Daniel Thompson', 'Blues');
insert into songs (Title, Artist, Genre) values ('Sapphire Skies', 'Sophia Garcia', 'Country');
insert into songs (Title, Artist, Genre) values ('Ocean Waves', 'Alexander Cruz', 'Country');
insert into songs (Title, Artist, Genre) values ('Fireside Serenade', 'Owen Stewart', 'Country');
insert into songs (Title, Artist, Genre) values ('Serenity Song', 'Olivia Martinez', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Sunset Dreams', 'Olivia Martinez', 'Rock');
insert into songs (Title, Artist, Genre) values ('Midnight Serenade', 'Ava Hernandez', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Olivia Martinez', 'Metal');
insert into songs (Title, Artist, Genre) values ('Midnight Serenade', 'Michael Brown', 'EDM');
insert into songs (Title, Artist, Genre) values ('Whispers in the Wind', 'Ella Murphy', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Cascade of Dreams', 'Matthew Lopez', 'Pop');
insert into songs (Title, Artist, Genre) values ('Summer Breeze', 'Ethan Ramirez', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Summer Breeze', 'Alice Smith', 'Country');
insert into songs (Title, Artist, Genre) values ('Lavender Lullaby', 'Charlotte Flores', 'Classical');
insert into songs (Title, Artist, Genre) values ('Luminous Lullaby', 'Michael Brown', 'Indie');
insert into songs (Title, Artist, Genre) values ('Melancholy Melody', 'Henry Reed', 'Soul');
insert into songs (Title, Artist, Genre) values ('Ethereal Echo', 'Emily Davis', 'Blues');
insert into songs (Title, Artist, Genre) values ('Siren''s Song', 'Amelia Adams', 'Soul');
insert into songs (Title, Artist, Genre) values ('Siren''s Song', 'Luna Cooper', 'Indie');
insert into songs (Title, Artist, Genre) values ('Ethereal Echo', 'John Johnson', 'Country');
insert into songs (Title, Artist, Genre) values ('Eternal Embrace', 'Emily Davis', 'Metal');
insert into songs (Title, Artist, Genre) values ('Enigma Elegy', 'David Wilson', 'Punk');
insert into songs (Title, Artist, Genre) values ('Majestic Melody', 'Ava Hernandez', 'R&B');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Olivia Martinez', 'Rock');
insert into songs (Title, Artist, Genre) values ('Infinite Illusion', 'Michael Brown', 'Hip Hop');
